name: localize_and_translate_example
description: Example for how to use the localize_and_translate plugin.
publish_to: 'none'


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  print_color: any
  localize_and_translate:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/ar.json