name: localize_and_translate_example
description: Example for how to use the localize_and_translate plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  localize_and_translate:
    path: ../

flutter:
  uses-material-design: true