name: localize_and_translate
description: Flutter localization in easy steps, simple ways to localize and translate your app
version: 5.0.13-dev
homepage: https://github.com/msayed-net/localize_and_translate
issue_tracker: https://github.com/msayed-net/localize_and_translate/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  assets:
    - lang/
