name: localize_and_translate
description: Flutter localization in easy steps, simple ways to localize and translate your app
version: 6.0.0-dev.1
homepage: https://github.com/msayed-net/localize_and_translate
issue_tracker: https://github.com/msayed-net/localize_and_translate/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
