name: localize_and_translate
description: Flutter Localization In Human Way, Help with localizing your app 
version: 3.0.0
homepage: https://github.com/msayed-net/localize_and_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  intl: ^0.16.0
  http: ^0.12.1
  # translator: ^0.1.4


