name: localize_and_translate
description: Flutter localization in easy steps, simple ways to localize and translate your app
version: 3.0.1
homepage: https://github.com/msayed-net/localize_and_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  intl: ^0.16.0
  http: ^0.12.2
  devicelocale: ^0.3.1



