name: localize_and_translate
description: Flutter localization in easy steps, simple ways to localize and translate your app
version: 5.0.0-dev
homepage: https://github.com/msayed-net/localize_and_translate
issue_tracker: https://github.com/msayed-net/localize_and_translate/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ">=2.0.0 <3.0.0"
  intl: ">=0.17.0-0 <=0.17.0"
  args: ^2.3.1
  path: ^1.8.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

flutter:
  assets:
    - lang/
